/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HHeader: typeof import('./../components/HHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    UApp: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_typescript@5.8.2_v_4b46b36f8592c8362dea6df5663769d8/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_typescript@5.8.2_v_4b46b36f8592c8362dea6df5663769d8/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_typescript@5.8.2_v_4b46b36f8592c8362dea6df5663769d8/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    ULinkBase: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_typescript@5.8.2_v_4b46b36f8592c8362dea6df5663769d8/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UNavigationMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parser@7.27.0_axios@1.8.4_embla-carousel@8.5.2_typescript@5.8.2_v_4b46b36f8592c8362dea6df5663769d8/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  }
}
