name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.event_name != 'pull_request') || github.event_name == 'pull_request'
    strategy:
      matrix:
        node: [22]
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: npm test

      - name: Run build
        run: npm run build
